data:
  TRAIN_IMG_DIR  : "./data/train/train/imgs"
  TEST_IMG_DIR  : "./data/PublicData/PublicTest"
  T2I_JSON  : "./data/train/train/t2i.json"
  T2I_CSV  : "./data/Track3_Public/t2i.csv"
  OUTPUT_DIR : "./data/dataset"
  RESULT_TOP_K: "./data/result"

  TRAIN_CSV: "./data/dataset/train.csv"
  VAL_CSV: "./data/dataset/val.csv"
  TEST_CSV: "./data/dataset/test.csv"

  DRIVE_URL: "https://drive.google.com/drive/folders/1MHfq2L8q1yq9UIia6UB1zLB-iLDh76vl?hl=vi"
  DOWNLOADED_FILES: "./data/downloaded_files"
  LIST_IMAGES: "./data/downloaded_files/ENTRep_Private_Dataset/ENTRep Private Dataset"

  RERANK_POSFUSE_DIR: "./data/rerank_posfuse_result"
  RERANK_POSFUSE_JSON_DIR: "./data/rerank_posfuse_result/combine_gemini.json"
  

logging:
  save_dir: "./checkpoints/nano_clip/logs"

VAL_RATIO : 0.1

TRAIN:
  resize: [256, 256]
  crop: [224, 224]
  crop_scale: [0.8, 1.0]
  rotation: 10
  flip_prob: 0.3
  color_jitter:
    brightness: 0.1
    contrast: 0.1
  random_erasing:
    p: 0.3
    scale: [0.02, 0.08]
    ratio: [0.3, 3.3]

VALID:
  resize: [224, 224]

MODEL:
  ViT_encoder: "dinov2_vits14"
  Lang_encoder: "sentence-transformers/all-MiniLM-L6-v2"
  max_length: 128
  embed_size: 64
  unfreeze_n_blocks: 4

OPTIMIZER:
  lr: 5e-5
  weight_decay: 1e-3
  warmup_epochs: 2
  milestones: [10, 20, 30]
  lr_mult: 0.1

TRAINING:
  precision: "16-mixed"
  max_epochs: 10
  check_val_every_n_epoch: 2
  log_every_n_steps: 10
  fast_dev_run: False

DEVICE:
  preferred: "cuda:0"
